-- AlterTable
ALTER TABLE "UserInventory" ALTER COLUMN "backgroundIDs" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "ringIDs" SET DEFAULT ARRAY[]::INTEGER[],
ALTER COLUMN "stickerIDs" SET DEFAULT ARRAY[]::INTEGER[];
